project:
  type: website
  output-dir: docs

website:
  title: "Amelia Ritger"
  navbar:
    background: "#F0EBDE"
    foreground: "#000000"
    search: true
    right:
      - text: Research
        href: research.qmd
      - text: Teaching
        href: teaching.qmd
      - text: Publications
        href: publications.qmd
      - text: Shiny
        href: shiny.qmd
      - text: About
        href: about.qmd
  page-footer: 
    background: "#F0EBDE"
    left: 
      - "Copyright 2022, Amelia Ritger"
    right:
      - <a href="https://github.com/ameliaritger/ameliaritger.github.io" target="_blank" style="color:#E84C22">Designed</a> with <a href="https://quarto.org/" target="_blank" style="color:#39729E">Quarto </a>
  
format:
  html:
    theme: 
    - darkly
    - custom.scss
    mainfont: "optima"
    fontcolor: "#000000"
    fontsize: 1.3em
    backgroundcolor: "#F0EBDE"
    margin-top: -30px
    margin-bottom: -10px
    linkcolor: "#CE5638"
    linestretch: 1.25
    toc: true

editor: visual