project:
  type: website
  output-dir: docs
  resources:
    - "files/cv.pdf"
    - "files/Ritger-and-Burnett-2024.pdf"
    - "files/Ritger-and-Burnett-2023.pdf"
    - "files/Hart-et-al-2023.pdf"
    - "files/Ingeman_et_al-2022-Scientific_Reports.pdf"
    - "files/Chandra et al 2018_Science.pdf"
    - "files/Ritger et al 2018_MPB.pdf"
    - "files/Ritger et al 2020_JEMBE.pdf"
    - "files/Trout-Haney2020_FreshwaterBiology.pdf"

website:
  title: "Amelia Ritger"
  navbar:
    background: "#F0EBDE"
    foreground: "#000000"
    search: true
    right:
      - text: Research
        href: research.qmd
      - text: Projects
        href: projects.qmd     
      - text: Publications
        href: publications.qmd
      - text: About
        href: about.qmd
  page-footer: 
    background: "#F0EBDE"
    left: 
      - "Copyright 2025, Amelia Ritger"
    right:
      - <a href='https://github.com/ameliaritger/ameliaritger.github.io' target='_blank' style='color:#E84C22'>Designed</a> with <a href='https://quarto.org/' target='_blank' style='color:#39729E'>Quarto</a>
  
format:
  html:
    theme: 
    - darkly
    - custom.scss
    mainfont: "optima"
    fontcolor: "#000000"
    fontsize: 1.2em
    backgroundcolor: "#F0EBDE"
    margin-top: -30px
    margin-bottom: -10px
    linkcolor: "#CE5638"
    linestretch: 1.2
    toc: true

editor: visual