---
title: "Publications"
toc: false

editor: visual
---

**Ritger, A.L.**, and Hofmann, G.H. Bringing Heatwaves into the Lab: A low-cost, open-source, and automated system to simulate realistic heating events in an experimental setting. Limnology and Oceanography: Methods.

Chan, K.Y.K., Kui, L., McDonald, A.M., **Ritger, A.L.**, and Hofmann, G.H. Coastal marine heatwaves in the Santa Barbara Channel: decadal trends and ecological implications. Frontiers in Marine Science.

**Ritger, A.L.** and Burnett, D.C. 2024. <a href="https://ieeexplore.ieee.org/document/10244512" target="_blank">A Wirelessly-Enabled, Power-Optimized, Low-Cost, and Open-Source Durafet-based pH Instrument for Continuous, Long Term Environmental Monitoring.</a> OCEANS 2024 - Singapore. 1-6. <a href="files/Ritger-and-Burnett-2024.pdf" target="_blank">PDF</a>

**Ritger, A.L.** and Burnett, D.C. 2023. <a href="https://ieeexplore.ieee.org/document/10244512" target="_blank">Developing Low-Cost, Simplified, and Open-Source Durafet-based pH Instrument Electronics.</a> OCEANS 2023 - Limerick. 1-7. <a href="files/Ritger-and-Burnett-2023.pdf" target="_blank">PDF</a>

Hart, T., Frank, D., Lopes, L.E., Olivos-Cisneros, L., Lacy, K.D., Trible, W., **Ritger, A.**, Valdés-Rodríguez, S., and Kronauer, D.J.C. 2023. <a href="https://www.cell.com/cell/fulltext/S0092-8674(23)00544-5" target="_blank">Sparse and stereotyped encoding implicates a core glomerulus for ant alarm behavior.</a> Cell 186: 1-16. <a href="files/Hart-et-al-2023.pdf" target="_blank">PDF</a>

Ingeman, K.E., Zhao, L.Z., Wolf, C., Williams, D.R., **Ritger, A.L.**, Ripple, W.J., Kopecky, K.L., Dillon, E.M., DiFiore, B.P., Curtis, J.S., Csik, S.R., Bui, A., and Stier, A.C. 2022. <a href="https://www.nature.com/articles/s41598-022-13671-7" target="_blank">Glimmers of hope in large carnivore recoveries.</a> Scientific Reports 12(1): 1-13. <a href="files/Ingeman_et_al-2022-Scientific_Reports.pdf" target="_blank">PDF</a>

Trout-Haney, J.V., **Ritger, A.L.**, and Cottingham, K.L. 2021. <a href="https://onlinelibrary.wiley.com/doi/abs/10.1111/fwb.13636
" target="_blank">Benthic cyanobacteria of the genus *Nostoc* are a source of microcystins in Greenlandic lakes and ponds.</a> Freshwater Biology 66: 266-277. <a href="files/Trout-Haney2020_FreshwaterBiology.pdf" target="_blank">PDF</a>

**Ritger, A.L.**, Fountain, T.C., Bourne, K., Martín-Fernández, J.A., and Pierotti, M.E.R. 2020. <a href="https://www.sciencedirect.com/science/article/abs/pii/S0022098119303296" target="_blank">Diet choice in a generalist predator, the invasive lionfish (*Pterois volitans/miles*).</a> Journal of Experimental Marine Biology and Ecology 524: 151311. `<a href="files/Ritger et al 2020_JEMBE.pdf" target="_blank"`{=html}

Chandra, V., Fetter-Pruneda, I., Oxley, P.R., **Ritger, A.L.**, McKenzie, S.K., Libbrecht, R., and Kronauer, D.J.C. 2018. <a href="https://www.science.org/doi/10.1126/science.aar5723" target="_blank">Social regulation of insulin signaling and the evolution of eusociality in ants.</a> Science 361(6400): 398-402. <a href="files/Chandra et al 2018_Science.pdf" target="_blank">PDF</a>

**Ritger, A.L.**, Curtis, A., and Chen, C.Y. 2018. <a href="https://www.sciencedirect.com/science/article/abs/pii/S0025326X18301991" target="_blank">Bioaccumulation of mercury and other metal contaminants in invasive lionfish (*Pterois volitans/miles*) from Curaçao.</a> Marine Pollution Bulletin 131: 38-44. <a href="files/Ritger et al 2018_MPB.pdf" target="_blank">PDF</a>
